### ISSUE TITLE
the Issuer has not made this pass available to you ?

### ISSUE THREAD

**Issue by ag039st** [google-pay/wallet-samples#25]
Im getting this after using the proper JWT setup  any Idea what probably missing 

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/103463536/186965155-b766c44d-eb50-461c-8f0d-226c8b569d4d.png">

**Comment by ag039st** [comment]
https://pay.google.com/gp/v/save/eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJ0bi1hYmMtdGVzdEB2aWJyYW50LXJldGluYS0yODAzMTQuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJhdWQiOiJnb29nbGUiLCJ0eXAiOiJzYXZldG93YWxsZXQiLCJpYXQiOjE2NjE1MzY5MTMsInBheWxvYWQiOnsiZ2VuZXJpY09iamVjdHMiOlt7ImlkIjoiMzM4ODAwMDAwMDAyMjEyODY0OC5QRVJTRVItTUFDLTIxMDAwMjAifV19LCJvcmlnaW5zIjpbXX0.nrtVK_cjRNXSs4bckw1U1b8A1YtccxTV5oF25fop-YnJBMItWxUSy5mW1hKX6ywyJvl3BT9UV7GiIa16LcLDQWfPc6UlxCHBzNe4WR_uNpofqLD0Z71vv3-nrDMc1WOAMZFAhqWAzvCu-i_HI_wVHIQ41dANnsIZ1Oqz5lYLq4lhxhCpfnyDlrh7ZDTTpKx2zsiiKdA7J2Ixhm6bZ9qxAP-TyOvAIMBYaW_Jv8O0WAJdrX9DKh53gonEWXo-GQUZmWl3gVJk8zqLnJdpyZH7uEnSUq0mG1cVAj0HyyAxdDaEuZrgnL414e04hCqXcHAuByRpFLUS5-eCAkzysbEqkA

**Comment by ncalteen** [comment]
Hello,

Apologies for the delay getting back to you on this. My initial thought was that the issue could be related to invalid time intervals for the pass object. In testing, however, I was unable to reproduce the issue.

Would you be able to provide the pass object definition (removing any sensitive data)?

**Comment by ncalteen** [comment]
Hello again,

After doing some further research, this may be your issuer account being in developer mode. The best course of action would be to contact [Google Wallet support](https://support.google.com/google-pay-and-wallet-console/answer/10913634) to assist.

**Comment by ag039st** [comment]
hi @ncalteen  all good now , you 're the issuer account was not properly setup, but once google approved the account all went fine

**Comment by ncalteen** [comment]
I'll reopen this issue and test it out. I'll send another response soon!

**Comment by ncalteen** [comment]
I did some testing and came to the following results:

If I create a temporary issuer account using my regular email, I get a "something went wrong" error when using the JWT creation methods in this repository (testing with the Python [`create_jwt_save_url`](https://github.com/google-pay/wallet-samples/blob/main/python/demo_generic.py#L218) method). This is because the JWT is signed by the service account key used in the [`auth`](https://github.com/google-pay/wallet-samples/blob/main/python/demo_generic.py#L52) method, which does not have permissions to the temporary issuer account.

However, if I create the temporary issuer account using my service account email, I get the same error as you. This is because the temporary issuer accounts are in developer mode (the same issue you faced originally). They are intentionally set up this way, so only email addresses that have permissions to the issuer account are able to save the passes.

___

One solution that could work in your case would be to create another issuer account that is a "child" of your main issuer account. This way you do not need to populate your main issuer account with test passes. When you create a new issuer account using one that is already approved, it will also be approved automatically. The steps below outline how to do this:

1. Using your service account credentials and your existing issuer account, call [`create_issuer_account`](https://github.com/google-pay/wallet-samples/blob/main/python/demo_generic.py#L355) to create a new issuer account. Make sure to give it a name and email that identify it as used for testing.

    ```python
    new_issuer_id = demo.create_issuer_account(issuer_name="MyCompany - TEST",
                                               issuer_email="myemail+test@example.com")
    ```

2. Next, update the permissions of the issuer account to include any email addresses that need access to create/edit passes.

    ```python
    demo.update_issuer_account_permissions(issuer_id=new_issuer_id,
                                           permissions:[
                                               {
                                                   "emailAddress": "service-account@example.com",
                                                   "role": "OWNER"
                                               }, # repeat for each email/role
                                           ])
    ```

After that, you should be able to use this issuer ID for testing purposes.

Please let me know if this helps, and if you have any other questions!

**Comment by ncalteen** [comment]
How long ago did you create the temporary issuer account? They are only valid for 7 days.

Also, the `create_issuer_account` call must be made with a service account associated with a non-temporary issuer account (one you created in the Google Pay and Wallet Console).

**Comment by ncalteen** [comment]
Hello,

If the calling issuer account is in developer mode, then any accounts it creates will also be in developer mode. In order to create production issuer accounts, you would first need a production account. To get the first one, you would need to reach out to Google Support. If you go into the [Google Pay & Wallet Console](https://pay.google.com/business/console/home), the **Contact support** option should get you in contact with someone who can help you with getting the main account approved.

I hope this helps!
