### ISSUE TITLE
Generic Pass Upcoming Notifications  .NET Core

### ISSUE THREAD

**Issue by DboukAli98** [google-pay/wallet-samples#47]
Greetings, I have successfully integrated the google wallet API in my .NET Core application and used the generic pass template.
I need to know how to implement the upcoming notifications feature in it, I have seen the official wallet documentation but couldn't figure it out if anyone has implemented it. I really appreciate any help I can get.

**Comment by ncalteen** [comment]
Hello,

Congratulations on integrating Google Wallet into your application :)

There are two main properties that must be set in a pass object to enable upcoming notifications:

* `genericobject.notifications`
* `genericobject.validTimeInterval`

There are a couple important things to consider when setting these:

* This is configured on the pass **object**, not on the pass **class**.
* Make sure to specify the fully-qualified class for any `Google.Apis.Walletobjects.v1.Data.DateTime` fields (so they aren't confused with `System.DateTime`).
* In the `notifications` configuration, `expiryNotification` takes precedence over `upcomingNotification`. If you plan to set `expiryNotification`, setting `upcomingNotification` will have no effect.
* The `start` property of `validTimeInterval` must be set for `upcomingNotification` to work.
* Including an offset in the value of the `start` property will make it a specific time across the entire world. If you do not include an offset, the time will be for the local time zone the pass holder is in.

I've included a basic generic pass object definition below that includes the needed settings. Please give it a try and let me know if you run into any trouble!

```csharp
GenericObject genericObject = new GenericObject
{
  Id = $"{issuerId}.{objectSuffix}",
  ClassId = $"{issuerId}.{classSuffix}",
  CardTitle = new LocalizedString
  {
    DefaultValue = new TranslatedString
    {
      Language = "en-US",
      Value = "Demo GenericObject Notifications"
    }
  },
  Header = new LocalizedString
  {
    DefaultValue = new TranslatedString
    {
      Language = "en-US",
      Value = "DboukAli98"
    }
  },
  Notifications = new Notifications
  {
    UpcomingNotification = new UpcomingNotification
    {
      EnableNotification = true
    }
  },
  ValidTimeInterval = new TimeInterval
  {
    Start = new Google.Apis.Walletobjects.v1.Data.DateTime
    {
      Date = "2022-11-15T10:30:00.00"
    }
  }
};
```

**Comment by DboukAli98** [comment]
Thank you very much  @ncalteen !  
One last question what is the AddMessage property in Loyalty Pass ? I'll be glad to know more , because the official documentation is really ambiguous .
Thanks once again for your help,

**Comment by DboukAli98** [comment]
And another thing can upcoming notifications be customized or they are not customizable?

**Comment by ncalteen** [comment]
I'm happy to help! :)

The `AddMessage` method lets you add text data to pass details. You can add messages either to classes or objects. Adding a message to a class will affect all pass holders, while adding a message to an object affects only the user(s) who have that specific object in their wallet.

When you add a message to a pass, it appears in the pass details section. I made a very simple example below. In this case, I have a loyalty card for my coffee shop (if only I could fit one in my office...) and want to let users know I have a new mocha available. I can add this message so it will appear in my pass details.

From the user's point of view, they will first open their pass in Google Wallet:

![pass_saved](https://user-images.githubusercontent.com/5089146/201966281-4a38b175-e9ab-480e-86b2-4629f69929e9.png)

Next, they will select Details and see the new message I added.

![pass_details](https://user-images.githubusercontent.com/5089146/201966529-ab38dbdc-9dee-4bf2-b420-4508b2fc439d.png)

The code to do this for a pass object is below. I'd recommend including an ID in the message so that they can be managed more easily, and making sure that the ID is not one that would likely be duplicated later (if this is something you plan to do).

```csharp
AddMessageRequest request = new AddMessageRequest
{
  Message = new Message
  {
    Id = "2022-11-15_MochaAnnouncement",
    Body = "Try our new Mocha today!"
  }
};

Stream responseStream = DemoLoyalty.service.Loyaltyobject
            .Addmessage(request, $"{issuerId}.{objectSuffix}")
            .ExecuteAsStream();
StreamReader responseReader = new StreamReader(responseStream);
JObject jsonResponse = JObject.Parse(responseReader.ReadToEnd());

Console.WriteLine("Message insert response");
Console.WriteLine(jsonResponse.ToString());
```

To answer your second question, notification text can't be customized currently. The specific text will always be:

* **Upcoming notification:** `genericObject.cardTitle is available now`
* **Expiry notification:** `genericObject.cardTitle expires in [x] days`

**Comment by DboukAli98** [comment]
Thanks very much @ncalteen  you really cleared the path!
