### ISSUE TITLE
Jar file is incompatible on java 8

### ISSUE THREAD

**Issue by thannareetrairaweewat** [google-pay/wallet-samples#53]
Hi,

We run into an issue while using the jar file below because it is compatible with java 11 or above. However, we are using java 8 on implementing the application. Do you have any maven dependency for the google-walletobjects that we can use? Or any jar file that is compatible with java 8.

[google-walletobjects-v1-rev_20221109-java.zip](https://github.com/google-pay/wallet-samples/files/10144707/google-walletobjects-v1-rev_20221109-java.zip)

Thank you!

**Comment by ncalteen** [comment]
Hello!

Unfortunately we do not have a Java 8-compatible JAR at this time. I will bring this up to the Engineering team to take a look at! In the meantime, you can continue to use the Google Wallet API, however you will need to instead build the API requests as JSON strings instead of using the object types defined by the library. An example can be found below:

```java
HttpTransport httpTransport = GoogleNetHttpTransport.newTrustedTransport();
HttpRequestFactory httpRequestFactory = httpTransport.createRequestFactory();

GenericUrl objectUrl = new GenericUrl(String.format("https://walletobjects.googleapis.com/walletobjects/v1/genericObject/%s.%s", issuerId, objectSuffix));

// Build a payload for an object
// Make sure to include all required properties
// for this object type
String objectPayload = String.format(
    "{"
  + "  \"id\": \"%s.%s\","
  + "  \"classId\": \"%s.%s\""
  + "}",
  issuerId, objectSuffix, issuerId, classSuffix);

// Check if the object exists already
// Build a GET request
HttpRequest objectRequest = httpRequestFactory.buildGetRequest(objectUrl);

// Add auth to the request headers
objectRequest
    .setHeaders(new HttpHeaders()
        .setAuthorization("Bearer " + credentials.getAccessToken().getTokenValue()));

// Invoke the GET request
HttpResponse objectResponse = objectRequest.execute();

if (objectResponse.getStatusCode() == 404) {
  // Object does not yet exist
  // Send POST request to create it
  // Include the JSON payload
  objectRequest = httpRequestFactory.buildPostRequest(
      objectUrl,
      new JsonHttpContent(new GsonFactory(), objectPayload));

  // Add auth to the request
  objectRequest
      .setHeaders(new HttpHeaders()
          .setAuthorization("Bearer " + credentials.getAccessToken().getTokenValue()));

  // Invoke the POST request
  objectResponse = objectRequest.execute();
}

System.out.println("object GET or POST response: " + objectResponse.parseAsString());
```

Additional examples can be found in this repo in earlier commits (before we updated it to use the Walletobjects library). Check out [this link](https://github.com/google-pay/wallet-samples/blob/a1a185d568a104e9e66c2eca35587ec79ab9a79b/java/src/main/java/DemoGeneric.java) for instance.

I hope this helps!

**Comment by ncalteen** [comment]
Hello again,

We haven't heard back from you in a while regarding this issue. I will go ahead and close this out for the time being. If you're still running into any problems, please feel free to reopen and add any additional details!
